favicon: https://bananayx.github.io/files/img/Banana头像.png
banner: 'https://bananayx.github.io/files/img/Banana Y.X.导航白字小尺寸.png'

logo:
  expanded: 'https://bananayx.github.io/files/img/Banana Y.X.导航白字小尺寸.png'
  collapsed: https://bananayx.github.io/files/img/Banana头像.png
  dark: 'https://bananayx.github.io/files/img/Banana Y.X.导航黑字小尺寸.png'

flag:
  - name: Chinese
    default: true
    icon: flag-cn
    index: /index.html

search: true

userDefinedSearchData:
  custom: false
  thisSearch: https://cn.bing.com/search?q=
  thisSearchIcon: url(https://cn.bing.com/favicon.ico)
  hotStatus: true
  data:
    - name: 必应
      img: url(https://cn.bing.com/favicon.ico)
      url: https://cn.bing.com/search?q=

githubCorner: '<a href="https://github.com/Bananayx" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

expandAll: false
menu:
  - name: 有关Banana Y.X.
    config: mysite
  - name: Banana Y.X.的资源分享
    config: myshare
  - name: AI工具
    config: ai
    submenu:
      - name: 全能
        config: ai-all
      - name: 对话
        config: ai-chat
      - name: 文章生成
        config: ai-text
      - name: 图像处理
        config: ai-image
      - name: 音频处理
        config: ai-audio
      - name: 数据处理
        config: ai-data
      - name: 开发者
        config: ai-dev
  - name: 游戏
    config: game
    submenu:
      - name: 在线游戏
        config: game-online
      - name: 游戏工具
        config: game-tool
      - name: 游戏资源
        config: game-res
      - name: 游戏教程

game-online:
  - name: '一起玩红白机'
    url: 'https://www.playfc.cn'
    img: 'https://www.playfc.cn/favicon.ico'
    description: '“全网唯一可在线比拼分数的红白机网站”'
  - name: 'Return8090'
    url: 'https://www.return8090.com/'
    img: 'https://www.return8090.com/favicon.ico'
    description: '经典复古游戏机在线玩'
  - name: 'Play Subway Surfers Online'
    url: 'https://subway-surfers.me/'
    img: 'https://subway-surfers.me/favicon.ico'
    description: '在线玩地铁跑酷'
  - name: 'Игра Subway Surfers: Сан-Франциско - Играть Онлайн!'
    url: 'https://igroutka.ru/igry-subway-surfers/36834-subway-surfers-san-francisko.html'
    img: 'https://igroutka.ru/favicon.ico'
    description: '在线玩地铁跑酷'
  - name: 'Игра Subway Surfers: Цюрих - Играть Онлайн!'
    url: 'https://igroutka.ru/igry-subway-surfers/36819-sabfey-serfers.html'
    img: 'https://igroutka.ru/favicon.ico'
    description: '在线玩地铁跑酷'
  - name: 'Poki(宝玩)'
    url: 'https://poki.com/zh'
    img: 'https://a.poki-cdn.com/icons/favicon-194x194.png'
    description: '免费在线小游戏 - 马上玩！'
  - name: 'js13kGames'
    url: 'https://js13kgames.com/'
    img: 'https://byxfiles.pages.dev/img/js13kgames_f32.png'
    description: 'HTML5 and JavaScript Game Development Competition in just 13 kilobytes'
  - name: '局部战争Local War'
    url: 'https://localwar.xidayun.com/'
    img: 'https://byxfiles.pages.dev/img/FluentGlobe24Regular.svg'
    description: '多人FPS射击页游'
  - name: 'Y8.com'
    url: 'https://zh.y8.com/'
    img: 'https://zh.y8.com/favicon.ico'
    description: '适合所有年龄的免费线上游戏 - 今天就来体验！'
  - name: 'Silvergames.com'
    url: 'https://www.silvergames.com/zh/'
    img: 'https://www.silvergames.com/favicon.ico'
    description: '玩最好的在线游戏'
  - name: 'Yandex游戏'
    url: 'https://yandex.com/games/'
    img: 'https://yandex.com/games/favicon.ico'
    description: '适合各种口味的免费在线游戏。无需下载。'
  - name: 'Oasis AI Minecraft'
    url: 'https://mine-oasis.com/zh'
    img: 'https://byxfiles.pages.dev/img/mine-oasis_favicon.ico'
    description: '動態AI生成的Minecraft'

ai-dev:
  - name: 'Zread'
    url: 'https://zread.ai/'
    img: 'https://zread.ai/favicon.ico'
    description: '专为开发者设计的AI源码解读产品'

ai-data:
  - name: 'ChatExcel'
    url: 'https://chatexcel.com/'
    img: 'https://chatexcel.com/logo.svg'
    description: 'AI表格处理与数据分析'

ai-audio:
  - name: 'Reecho睿声'
    url: 'https://www.reecho.cn/'
    img: 'https://www.reecho.cn/images/favicon.png'
    description: '超拟真语音合成与瞬时克隆平台'
  - name: '马克配音'
    url: 'https://ttsmaker.cn/'
    img: 'https://ttsmaker.cn/favicon.ico'
    description: '在线免费文字转语音'
  - name: '音子AI'
    url: 'https://www2.yinziai.com/'
    img: 'https://www2.yinziai.com/favicon.ico'
    description: '在线免费人声分离、伴奏分离器'
  - name: 'LALAL.AI'
    url: 'https://www.lalal.ai/zh-hans/'
    img: 'https://www.lalal.ai/favicon.ico'
    description: '人声去除器和AI智能伴奏分离器'

ai-image:
  - name: 'remove.bg'
    url: 'https://www.remove.bg/'
    img: 'https://www.remove.bg/favicon.ico'
    description: '在线抠图软件_图片去除背景'
  - name: '佐糖'
    url: 'https://picwish.cn/'
    img: 'https://qncdn.aoscdn.com/astro/picwish/_astro/favicon@30w.61721eae.png'
    description: '在线图片处理工具_在线抠图_证件照换底色_去水印_照片修复'
  - name: '吐司'
    url: 'https://tusi.cn/'
    img: 'https://tusi.cn/favicon.ico'
    description: '可在线生图的 AI 模型分享社区，还是免费的！'
  - name: 'Magic Eraser'
    url: 'https://magicstudio.com/zh/magiceraser/'
    img: 'https://magicstudio.com/favicon.ico'
    description: '删除照片中的物体 | Magic Eraser by Magic Studio'

ai-text:
  - name: 'EffiditAI作文'
    url: 'https://effidit.qq.com/demo'
    img: 'https://effidit.qq.com/favicon.png'
    description: '智能创作助手 Effidit 是由腾讯 AI Lab 开发的一个研究性原型系统，探索用 AI 技术提升写作者的写作效率和创作体验。'
  - name: 'East.im'
    url: 'https://east.im/'
    img : 'https://east.im/favicon.ico'
    description: '文章生成器，一键智能扩写和AI中文润色, 自动AI写作'

ai-chat:
  - name: 'DeepSeek'
    url: 'https://chat.deepseek.com/'
    img: 'https://chat.deepseek.com/favicon.svg'
    description: 'DeepSeek - 探索未至之境'

ai-all:
  - name: '豆包'
    url: 'https://www.doubao.com/'
    img: 'https://lf-flow-web-cdn.doubao.com/obj/flow-doubao/doubao/web/logo-icon.png'
    description: '字节跳动旗下AI智能助手'
  - name: '墨墨AI'
    url: 'https://ai.codinghou.cn/'
    img: 'https://ai.codinghou.cn/favicon.ico'
    description: '一站式体验/学习/使用AI'
  - name: 'AI Tools'
    url: 'https://abc.ufun.net/'
    img: 'https://abc.ufun.net/favicon.ico'
    description: 'AI Tools'
  - name: '纳米AI'
    url: 'https://www.n.cn/'
    img: 'https://www.n.cn/favicon.ico'
    description: '360旗下 纳米AI'
  - name: '天工Agent版'
    url: 'https://www.tiangong.cn/'
    img: 'https://www.tiangong.cn/favicon.ico'
    description: 'TianGong - AI办公智能体先行者'
  
ai:
  - name: AI工具集
    url: 'https://ai-bot.cn/'
    img: 'https://ai-bot.cn/favicon.ico'
    description: 'AI工具集 | 700+ AI工具集合官网，国内外AI工具集导航大全'

myshare:
  - name: '系统镜像分享'
    url: 'https://cloud.aoe.top/s/g6rsv'
    img: 'https://mod.3dmgame.com/static/upload/mod/202211/MOD6386ccf455c06.png@webp'
    description: '感谢小莫云盘提供的文件存储及分享服务！'
  - name: '电影资源分享'
    url: 'https://cloud.aoe.top/s/KB4fO'
    img: 'https://mod.3dmgame.com/static/upload/mod/202211/MOD6386ccf455c06.png@webp'
    description: '感谢小莫云盘提供的文件存储及分享服务！'
  - name: '绿色软件分享'
    url: 'https://pan.huang1111.cn/s/XqxnGTl'
    img: 'https://a.h1static.cn/pan/Logohuang1111.ico'
    description: '感谢huang1111网盘提供的文件存储及分享服务！'
  - name: '音乐资源分享'
    url: 'https://008686.xyz/s/EVGBtQ'
    img: 'https://008686.xyz/static/img/favicon.ico'
    description: '感谢扒拉云盘提供的文件存储及分享服务！'
  - name: '我的录屏备份'
    url: 'https://008686.xyz/s/6bkdfx'
    img: 'https://008686.xyz/static/img/favicon.ico'
    description: '感谢扒拉云盘提供的文件存储及分享服务！'
  - name: '我的剪辑备份'
    url: 'https://008686.xyz/s/1RWxSN'
    img: 'https://008686.xyz/static/img/favicon.ico'
    description: '感谢扒拉云盘提供的文件存储及分享服务！'
  - name: '我某次拍的风景1'
    url: 'https://photo.baidu.com/photo/wap/albumShare/invite/jFxajRFOWW?from=webcreate'
    img: 'https://staticsns.cdn.bcebos.com/amis/2023-2/1676342310828/favicon.ico'
    description: '感谢一刻相册提供的照片存储及分享服务！'
  - name: '我某次拍的风景2'
    url: 'https://photo.baidu.com/photo/wap/albumShare/invite/jhsxVrGOJm?from=webcreate'
    img: 'https://staticsns.cdn.bcebos.com/amis/2023-2/1676342310828/favicon.ico'
    description: '感谢一刻相册提供的照片存储及分享服务！'
  - name: '我某次拍的风景3'
    url: 'https://photo.baidu.com/photo/wap/albumShare/invite/jgePIuYfka?from=webcreate'
    img: 'https://staticsns.cdn.bcebos.com/amis/2023-2/1676342310828/favicon.ico'
    description: '感谢一刻相册提供的照片存储及分享服务！'
  - name: '我某次拍的风景4'
    url: 'https://photo.baidu.com/photo/wap/albumShare/invite/OnhpQsIjoC?from=webcreate'
    img: 'https://staticsns.cdn.bcebos.com/amis/2023-2/1676342310828/favicon.ico'
    description: '感谢一刻相册提供的照片存储及分享服务！'
  - name: '某四张壁纸'
    url: 'https://photo.baidu.com/photo/wap/albumShare/invite/UKKIZXndKS?from=webcreate'
    img: 'https://staticsns.cdn.bcebos.com/amis/2023-2/1676342310828/favicon.ico'
    description: '感谢一刻相册提供的照片存储及分享服务！'
  - name: '必应壁纸收藏1'
    url: 'https://photo.baidu.com/photo/wap/albumShare/invite/MjmfzIJbNa?from=webcreate'
    img: 'https://staticsns.cdn.bcebos.com/amis/2023-2/1676342310828/favicon.ico'
    description: '感谢一刻相册提供的照片存储及分享服务！'
  - name: '必应壁纸收藏2'
    url: 'https://photo.baidu.com/photo/wap/albumShare/invite/PqsnSPfFeu?from=webcreate'
    img: 'https://staticsns.cdn.bcebos.com/amis/2023-2/1676342310828/favicon.ico'
    description: '感谢一刻相册提供的照片存储及分享服务！'
  - name: 'Windows 11概念壁纸收藏'
    url: 'https://photo.baidu.com/photo/wap/albumShare/invite/btreUoaYv?from=webcreate'
    img: 'https://staticsns.cdn.bcebos.com/amis/2023-2/1676342310828/favicon.ico'
    description: '感谢一刻相册提供的照片存储及分享服务！'
  - name: 'Windows 11自带壁纸'
    url: 'https://photo.baidu.com/photo/wap/albumShare/invite/RnfWhLYJMl?from=webcreate'
    img: 'https://staticsns.cdn.bcebos.com/amis/2023-2/1676342310828/favicon.ico'
    description: '感谢一刻相册提供的照片存储及分享服务！'
  - name: 'Windows聚焦壁纸收藏'
    url: 'https://photo.baidu.com/photo/wap/albumShare/invite/jnrYLNQYQn?from=webcreate'
    img: 'https://staticsns.cdn.bcebos.com/amis/2023-2/1676342310828/favicon.ico'
    description: '感谢一刻相册提供的照片存储及分享服务！'

mysite:
  - name: 'Banana Y.X.的小站'
    url: 'https://bananayx.github.io/'
    img: 'https://bananayx.github.io/files/img/Banana头像.png'
    description: '小站，大世界。'
  - name: 'Banana Y.X.的博客'
    url: 'https://bananayx.github.io/blog/'
    img: 'https://bananayx.github.io/files/img/Banana头像.png'
    description: '面朝大海，春暖花开。'
  - name: 'Banana Y.X.网盘'
    url: 'http://sj.frp.one:29552/'
    img: 'https://bananayx.github.io/files/img/Banana头像.png'
    description: '吹牛逼呢！这叫私人网盘，你会搭吗？你只能看着我，装逼！呵呵哈哈，加纳！'
  - name: 'Banana Y.X.的抖音'
    url: 'https://www.douyin.com/user/MS4wLjABAAAA0y-EB2FwDesDJnUjwTTJJU7uuvcOaIHr07y0bAFh_Wk'
    img: 'https://www.douyin.com/favicon.ico'
    description: '抖音，记录生活，分享快乐。'
  - name: 'Banana Y.X.的画廊(国内无法访问)'
    url: 'https://www.flickr.com/photos/bananayx/'
    img: 'https://bananayx.github.io/files/img/flickerfavicon.ico'
    description: 'Flicker，管理相片的新方式'

since: 2025

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /nav/js/bootstrap.min.js
  TweenMax: /nav/js/TweenMax.min.js
  resizeable: /nav/js/resizeable.min.js
  joinable: /nav/js/joinable.js
  xenonApi: /nav/js/xenon-api.min.js
  xenonToggles: /nav/js/xenon-toggles.min.js
  xenonCustom: /nav/js/xenon-custom.min.js
  lozad: /nav/js/lozad.min.js
  html5shiv: /nav/js/html5shiv.min.js
  respond: /nav/js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
